name: build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        working-directory: ${{github.workspace}}
        run: |
          JOBS=$(($(grep cpu.cores /proc/cpuinfo | sort -u | sed 's/[^0-9]//g') + 1))
          cmake -S . -B build -DBUILD_EXAMPLES=OFF
          cmake --build build -j${JOBS}
          sudo cmake --install build